/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\3D\NEXUM-BASE-3.glb -t 
*/

import * as THREE from 'three'
import React, { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Curve001: THREE.Mesh
    Curve002: THREE.Mesh
    Curve003: THREE.Mesh
    Curve008: THREE.Mesh
    Curve010: THREE.Mesh
  }
  materials: {
    MetalOxidado: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3D/NEXUM-BASE-3.glb') as GLTFResult

  // Clona el material y activa el wireframe
  const wireframeMaterial = materials.MetalOxidado.clone()
  wireframeMaterial.wireframe = true
  wireframeMaterial.wireframeLinewidth = 4 // Opcional: ajusta el grosor de las líneas
  wireframeMaterial.color.set('white') // Opcional: para un color de líneas claro

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Curve001.geometry}
        material={wireframeMaterial}
        position={[-0.061, 0.056, -0.037]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.283}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={wireframeMaterial}
        position={[-0.061, 0.056, -0.037]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.283}
      />
      <mesh
        geometry={nodes.Curve003.geometry}
        material={wireframeMaterial}
        position={[-0.061, 0.056, -0.037]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.283}
      />
      <mesh
        geometry={nodes.Curve008.geometry}
        material={wireframeMaterial}
        position={[-0.061, 0.056, -0.037]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={18.283}
      />
      <mesh geometry={nodes.Curve010.geometry} material={wireframeMaterial} />
    </group>
  )
}
