export function getFlagEmoji(countryCode: string): string {
  return countryCode
    .toUpperCase()
    .split("")
    .map((char) => String.fromCodePoint(127397 + char.charCodeAt(0)))
    .join("");
}

export const PHONE_CODES: Record<string, string> = {
  AC: "+247", AD: "+376", AE: "+971", AF: "+93",  AG: "+1-268",
  AI: "+1-264", AL: "+355", AM: "+374", AO: "+244", AQ: "+672",
  AR: "+54",  AS: "+1-684", AT: "+43",  AU: "+61",  AW: "+297",
  AX: "+358", AZ: "+994", BA: "+387", BB: "+1-246", BD: "+880",
  BE: "+32",  BF: "+226", BG: "+359", BH: "+973", BI: "+257",
  BJ: "+229", BL: "+590", BM: "+1-441", BN: "+673", BO: "+591",
  BQ: "+599", BR: "+55",  BS: "+1-242", BT: "+975", BW: "+267",
  BY: "+375", BZ: "+501", CA: "+1",   CC: "+61",  CD: "+243",
  CF: "+236", CG: "+242", CH: "+41",  CI: "+225", CK: "+682",
  CL: "+56",  CM: "+237", CN: "+86",  CO: "+57",  CR: "+506",
  CU: "+53",  CV: "+238", CW: "+599", CX: "+61",  CY: "+357",
  CZ: "+420", DE: "+49",  DJ: "+253", DK: "+45",  DM: "+1-767",
  DO: "+1-809",DZ: "+213", EC: "+593", EE: "+372", EG: "+20",
  EH: "+212", ER: "+291", ES: "+34",  ET: "+251", FI: "+358",
  FJ: "+679", FK: "+500", FM: "+691", FO: "+298", FR: "+33",
  GA: "+241", GB: "+44",  GD: "+1-473",GE: "+995", GF: "+594",
  GG: "+44",  GH: "+233", GI: "+350", GL: "+299", GM: "+220",
  GN: "+224", GP: "+590", GQ: "+240", GR: "+30",  GS: "+500",
  GT: "+502", GU: "+1-671",GW: "+245", GY: "+592", HK: "+852",
  HN: "+504", HR: "+385", HT: "+509", HU: "+36",  ID: "+62",
  IE: "+353", IL: "+972", IM: "+44",  IN: "+91",  IO: "+246",
  IQ: "+964", IR: "+98",  IS: "+354", IT: "+39",  JE: "+44",
  JM: "+1-876",JO: "+962", JP: "+81",  KE: "+254", KG: "+996",
  KH: "+855", KI: "+686", KM: "+269", KN: "+1-869",KP: "+850",
  KR: "+82",  KW: "+965", KY: "+1-345",KZ: "+7",   LA: "+856",
  LB: "+961", LC: "+1-758",LI: "+423", LK: "+94",  LR: "+231",
  LS: "+266", LT: "+370", LU: "+352", LV: "+371", LY: "+218",
  MA: "+212", MC: "+377", MD: "+373", ME: "+382", MF: "+590",
  MG: "+261", MH: "+692", MK: "+389", ML: "+223", MM: "+95",
  MN: "+976", MO: "+853", MP: "+1-670",MQ: "+596", MR: "+222",
  MS: "+1-664",MT: "+356", MU: "+230", MV: "+960", MW: "+265",
  MX: "+52",  MY: "+60",  MZ: "+258", NA: "+264", NC: "+687",
  NE: "+227", NF: "+672", NG: "+234", NI: "+505", NL: "+31",
  NO: "+47",  NP: "+977", NR: "+674", NU: "+683", NZ: "+64",
  OM: "+968", PA: "+507", PE: "+51",  PF: "+689", PG: "+675",
  PH: "+63",  PK: "+92",  PL: "+48",  PM: "+508", PN: "+870",
  PR: "+1-787",PS: "+970", PT: "+351", PW: "+680", PY: "+595",
  QA: "+974", RE: "+262", RO: "+40",  RS: "+381", RU: "+7",
  RW: "+250", SA: "+966", SB: "+677", SC: "+248", SD: "+249",
  SE: "+46",  SG: "+65",  SH: "+290", SI: "+386", SJ: "+47",
  SK: "+421", SL: "+232", SM: "+378", SN: "+221", SO: "+252",
  SR: "+597", SS: "+211", ST: "+239", SV: "+503", SX: "+1-721",
  SY: "+963", SZ: "+268", TC: "+1-649",TD: "+235", TF: "+262",
  TG: "+228", TH: "+66",  TJ: "+992", TK: "+690", TL: "+670",
  TM: "+993", TN: "+216", TO: "+676", TR: "+90",  TT: "+1-868",
  TV: "+688", TW: "+886", TZ: "+255", UA: "+380", UG: "+256",
  UM: "+1",   US: "+1",   UY: "+598", UZ: "+998", VA: "+379",
  VC: "+1-784",VE: "+58",  VG: "+1-284",VI: "+1-340",VN: "+84",
  VU: "+678", WF: "+681", WS: "+685", XK: "+383", YE: "+967",
  YT: "+262", ZA: "+27",  ZM: "+260", ZW: "+263",
};

export const CURRENCY_CODES: Record<string, string> = {
  AD: "EUR", AE: "AED", AF: "AFN", AG: "XCD", AL: "ALL", AM: "AMD",
  AO: "AOA", AR: "ARS", AT: "EUR", AU: "AUD", AZ: "AZN", BA: "BAM",
  BB: "BBD", BD: "BDT", BE: "EUR", BF: "XOF", BG: "BGN", BH: "BHD",
  BI: "BIF", BJ: "XOF", BN: "BND", BO: "BOB", BR: "BRL", BS: "BSD",
  BT: "BTN", BW: "BWP", BY: "BYN", BZ: "BZD", CA: "CAD", CD: "CDF",
  CF: "XAF", CG: "XAF", CH: "CHF", CI: "XOF", CL: "CLP", CM: "XAF",
  CN: "CNY", CO: "COP", CR: "CRC", CU: "CUP", CV: "CVE", CY: "EUR",
  CZ: "CZK", DE: "EUR", DJ: "DJF", DK: "DKK", DM: "XCD", DO: "DOP",
  DZ: "DZD", EC: "USD", EE: "EUR", EG: "EGP", ER: "ERN", ES: "EUR",
  ET: "ETB", FI: "EUR", FJ: "FJD", FK: "FKP", FM: "USD", FR: "EUR",
  GA: "XAF", GB: "GBP", GD: "XCD", GE: "GEL", GH: "GHS", GM: "GMD",
  GN: "GNF", GQ: "XAF", GR: "EUR", GT: "GTQ", GW: "XOF", GY: "GYD",
  HK: "HKD", HN: "HNL", HR: "EUR", HT: "HTG", HU: "HUF", ID: "IDR",
  IE: "EUR", IL: "ILS", IN: "INR", IQ: "IQD", IR: "IRR", IS: "ISK",
  IT: "EUR", JM: "JMD", JO: "JOD", JP: "JPY", KE: "KES", KG: "KGS",
  KH: "KHR", KI: "AUD", KM: "KMF", KN: "XCD", KP: "KPW", KR: "KRW",
  KW: "KWD", KY: "KYD", KZ: "KZT", LA: "LAK", LB: "LBP", LC: "XCD",
  LI: "CHF", LK: "LKR", LR: "LRD", LS: "LSL", LT: "EUR", LU: "EUR",
  LV: "EUR", LY: "LYD", MA: "MAD", MC: "EUR", MD: "MDL", ME: "EUR",
  MG: "MGA", MH: "USD", MK: "MKD", ML: "XOF", MM: "MMK", MN: "MNT",
  MO: "MOP", MR: "MRU", MT: "EUR", MU: "MUR", MV: "MVR", MW: "MWK",
  MX: "MXN", MY: "MYR", MZ: "MZN", NA: "NAD", NE: "XOF", NG: "NGN",
  NI: "NIO", NL: "EUR", NO: "NOK", NP: "NPR", NR: "AUD", NZ: "NZD",
  OM: "OMR", PA: "PAB", PE: "PEN", PG: "PGK", PH: "PHP", PK: "PKR",
  PL: "PLN", PT: "EUR", PW: "USD", PY: "PYG", QA: "QAR", RO: "RON",
  RS: "RSD", RU: "RUB", RW: "RWF", SA: "SAR", SB: "SBD", SC: "SCR",
  SD: "SDG", SE: "SEK", SG: "SGD", SH: "SHP", SI: "EUR", SK: "EUR",
  SL: "SLL", SM: "EUR", SN: "XOF", SO: "SOS", SR: "SRD", SS: "SSP",
  ST: "STN", SV: "USD", SY: "SYP", SZ: "SZL", TD: "XAF", TG: "XOF",
  TH: "THB", TJ: "TJS", TL: "USD", TM: "TMT", TN: "TND", TO: "TOP",
  TR: "TRY", TT: "TTD", TV: "AUD", TW: "TWD", TZ: "TZS", UA: "UAH",
  UG: "UGX", US: "USD", UY: "UYU", UZ: "UZS", VA: "EUR", VC: "XCD",
  VE: "VES", VN: "VND", VU: "VUV", WS: "WST", YE: "YER", ZA: "ZAR",
  ZM: "ZMW", ZW: "ZWL",
};

export const TIME_ZONES: Record<string, string> = {
  AD: "Europe/Andorra",       AE: "Asia/Dubai",           AF: "Asia/Kabul",
  AG: "America/Antigua",      AL: "Europe/Tirane",        AM: "Asia/Yerevan",
  AO: "Africa/Luanda",        AR: "America/Argentina/Buenos_Aires",
  AT: "Europe/Vienna",        AU: "Australia/Sydney",     AZ: "Asia/Baku",
  BA: "Europe/Sarajevo",      BB: "America/Barbados",     BD: "Asia/Dhaka",
  BE: "Europe/Brussels",      BF: "Africa/Ouagadougou",   BG: "Europe/Sofia",
  BH: "Asia/Bahrain",         BI: "Africa/Bujumbura",     BJ: "Africa/Porto-Novo",
  BN: "Asia/Brunei",          BO: "America/La_Paz",       BR: "America/Sao_Paulo",
  BS: "America/Nassau",       BT: "Asia/Thimphu",         BW: "Africa/Gaborone",
  BY: "Europe/Minsk",         BZ: "America/Belize",       CA: "America/Toronto",
  CD: "Africa/Kinshasa",      CF: "Africa/Bangui",        CG: "Africa/Brazzaville",
  CH: "Europe/Zurich",        CI: "Africa/Abidjan",       CL: "America/Santiago",
  CM: "Africa/Douala",        CN: "Asia/Shanghai",        CO: "America/Bogota",
  CR: "America/Costa_Rica",   CU: "America/Havana",       CV: "Atlantic/Cape_Verde",
  CY: "Asia/Nicosia",         CZ: "Europe/Prague",        DE: "Europe/Berlin",
  DJ: "Africa/Djibouti",      DK: "Europe/Copenhagen",    DM: "America/Dominica",
  DO: "America/Santo_Domingo",DZ: "Africa/Algiers",       EC: "America/Guayaquil",
  EE: "Europe/Tallinn",       EG: "Africa/Cairo",         ER: "Africa/Asmara",
  ES: "Europe/Madrid",        ET: "Africa/Addis_Ababa",   FI: "Europe/Helsinki",
  FJ: "Pacific/Fiji",         FM: "Pacific/Pohnpei",      FR: "Europe/Paris",
  GA: "Africa/Libreville",    GB: "Europe/London",        GD: "America/Grenada",
  GE: "Asia/Tbilisi",         GH: "Africa/Accra",         GM: "Africa/Banjul",
  GN: "Africa/Conakry",       GQ: "Africa/Malabo",        GR: "Europe/Athens",
  GT: "America/Guatemala",    GW: "Africa/Bissau",        GY: "America/Guyana",
  HK: "Asia/Hong_Kong",       HN: "America/Tegucigalpa",  HR: "Europe/Zagreb",
  HT: "America/Port-au-Prince",HU: "Europe/Budapest",    ID: "Asia/Jakarta",
  IE: "Europe/Dublin",        IL: "Asia/Jerusalem",       IN: "Asia/Kolkata",
  IQ: "Asia/Baghdad",         IR: "Asia/Tehran",          IS: "Atlantic/Reykjavik",
  IT: "Europe/Rome",          JM: "America/Jamaica",      JO: "Asia/Amman",
  JP: "Asia/Tokyo",           KE: "Africa/Nairobi",       KG: "Asia/Bishkek",
  KH: "Asia/Phnom_Penh",      KI: "Pacific/Tarawa",       KM: "Indian/Comoro",
  KN: "America/St_Kitts",     KP: "Asia/Pyongyang",       KR: "Asia/Seoul",
  KW: "Asia/Kuwait",          KZ: "Asia/Almaty",          LA: "Asia/Vientiane",
  LB: "Asia/Beirut",          LC: "America/St_Lucia",     LI: "Europe/Vaduz",
  LK: "Asia/Colombo",         LR: "Africa/Monrovia",      LS: "Africa/Maseru",
  LT: "Europe/Vilnius",       LU: "Europe/Luxembourg",    LV: "Europe/Riga",
  LY: "Africa/Tripoli",       MA: "Africa/Casablanca",    MC: "Europe/Monaco",
  MD: "Europe/Chisinau",      ME: "Europe/Podgorica",     MG: "Indian/Antananarivo",
  MK: "Europe/Skopje",        ML: "Africa/Bamako",        MM: "Asia/Rangoon",
  MN: "Asia/Ulaanbaatar",     MO: "Asia/Macau",           MR: "Africa/Nouakchott",
  MT: "Europe/Malta",         MU: "Indian/Mauritius",     MV: "Indian/Maldives",
  MW: "Africa/Blantyre",      MX: "America/Mexico_City",  MY: "Asia/Kuala_Lumpur",
  MZ: "Africa/Maputo",        NA: "Africa/Windhoek",      NE: "Africa/Niamey",
  NG: "Africa/Lagos",         NI: "America/Managua",      NL: "Europe/Amsterdam",
  NO: "Europe/Oslo",          NP: "Asia/Kathmandu",       NR: "Pacific/Nauru",
  NZ: "Pacific/Auckland",     OM: "Asia/Muscat",          PA: "America/Panama",
  PE: "America/Lima",         PG: "Pacific/Port_Moresby", PH: "Asia/Manila",
  PK: "Asia/Karachi",         PL: "Europe/Warsaw",        PT: "Europe/Lisbon",
  PW: "Pacific/Palau",        PY: "America/Asuncion",     QA: "Asia/Qatar",
  RO: "Europe/Bucharest",     RS: "Europe/Belgrade",      RU: "Europe/Moscow",
  RW: "Africa/Kigali",        SA: "Asia/Riyadh",          SB: "Pacific/Guadalcanal",
  SC: "Indian/Mahe",          SD: "Africa/Khartoum",      SE: "Europe/Stockholm",
  SG: "Asia/Singapore",       SI: "Europe/Ljubljana",     SK: "Europe/Bratislava",
  SL: "Africa/Freetown",      SM: "Europe/San_Marino",    SN: "Africa/Dakar",
  SO: "Africa/Mogadishu",     SR: "America/Paramaribo",   SS: "Africa/Juba",
  ST: "Africa/Sao_Tome",      SV: "America/El_Salvador",  SY: "Asia/Damascus",
  SZ: "Africa/Mbabane",       TD: "Africa/Ndjamena",      TG: "Africa/Lome",
  TH: "Asia/Bangkok",         TJ: "Asia/Dushanbe",        TL: "Asia/Dili",
  TM: "Asia/Ashgabat",        TN: "Africa/Tunis",         TO: "Pacific/Tongatapu",
  TR: "Europe/Istanbul",      TT: "America/Port_of_Spain",TV: "Pacific/Funafuti",
  TW: "Asia/Taipei",          TZ: "Africa/Dar_es_Salaam", UA: "Europe/Kiev",
  UG: "Africa/Kampala",       US: "America/New_York",     UY: "America/Montevideo",
  UZ: "Asia/Tashkent",        VA: "Europe/Vatican",       VC: "America/St_Vincent",
  VE: "America/Caracas",      VN: "Asia/Ho_Chi_Minh",     VU: "Pacific/Efate",
  WS: "Pacific/Apia",         YE: "Asia/Aden",            ZA: "Africa/Johannesburg",
  ZM: "Africa/Lusaka",        ZW: "Africa/Harare",
};
